project:
  type: website
  output-dir: docs

website:
  title: "Data Science Series"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - workshop1.qmd
      - workshop2.qmd
      - resources.qmd

format:
  html:
    theme: sandstone
    mainfont: arial
    fontsize: 1.5rem
    fontcolor: "#532912"
    linkcolor: "#d1672d"
    css: styles.css
    toc: true



