project:
  type: website
  output-dir: docs

website:
  favicon: bookfavicon.png
  title: "Data Science Series"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - workshop1.qmd
      - workshop2.qmd
      - workshop3.qmd
      - workshop4.qmd
      - resources.qmd
    background: "#532912"
    foreground: "#f5e0d5"

format:
  html:
    theme: 
     light: flatly
     dark: darkly
    mainfont: arial
    fontsize: 1rem
    fontcolor: "#b7b7a4"
    linkcolor: "#585123"
    css: styles.css
    toc: true



