project:
  type: website
  output-dir: docs

website:
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - Sign up for the upcoming workshops [here](https://libcal.uflib.ufl.edu/profile/104805)"
    type: primary
    position: below-navbar
  google-analytics: "G-L1G44K1ND2"
  favicon: bookfavicon.png
  title: "Data Science Series"
  sidebar:
    style: floating
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - section: "Workshop1"
        contents:
          - workshop1.qmd
      - section: "Workshop2"
        contents:
          - workshop2.qmd
      - section: "Workshop3"
        contents:
          - workshop3.qmd
      - section: "Workshop4"
        contents:
          - workshop4.qmd
      - section: "Workshop5"
        contents:
          - workshop5.qmd
      - section: "Resources"
        contents:
          - resources.qmd
    background: "#d0ebf1"
    foreground: "#000000"

format:
  html:
    theme: 
     light: flatly
     dark: darkly
    mainfont: arial
    fontsize: 1rem
    fontcolor: "#787894"
    linkcolor: "#a4b7a4"
    css: styles.css
    toc: true



